site_name: Agate examples
pages:
- Home: index.md
- Imports: imports.md
- Filters: filters.md
- Compute: compute.md
- Sorting: sort.md
- Rounding: rounding.md
- Distinct: distinct.md
- Jupyter: jupyter.md
theme: readthedocs
extra_css:
    - extra.css
